.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KOOD\-CARD" "1" "January 2013" "" ""
.
.SH "NAME"
\fBkood\-card\fR \- sample help page
.
.SH "SYNOPSIS"
A brief synopsis of how to invoke your app on the command line\. This should be similar to what the default banner is in OptionParser or what is output by GLI after the “Usage:” bit\.
.
.SH "DESCRIPTION"
A longer description of what your app does, why the user might use it, and any additional details\. This section should be targeted at new users and written to help them understand how to use your app\.
.
.SH "OPTIONS"
A bullet list documenting each option\. This is a chance to explain in more detail how the options work and what effect they have on your app’s behavior\.
.
.SH "EXAMPLES"
One or more examples of using the app, including brief text explaining each example\.
.
.SH "FILES"
A list of files on the filesystem that the app uses (for example, todo would document the default to\-do list file’s location here)\.
.
.SH "ENVIRONMENT"
A bullet list of any environment variables that affect the app’s behavior\.
.
.SH "BUGS"
Known bugs or odd behaviors\.
.
.SH "LICENSE"
The name of the license and a reference to the full license text (you do not need to reproduce the entire license here)\.
.
.SH "AUTHOR"
The authors of your app and their email addresses\.
.
.SH "COPYRIGHT"
The copyright information for your app\.
.
.SH "SEE ALSO"
Links to other commands or places on the Web that are relevant for your app\.
